
"""
Script generated by Mininet-GUI (https://github.com/latarc/mininet-gui)
"""
from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSKernelSwitch, OVSSwitch, OVSBridge, Host, Node, NOX, UserSwitch
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel
from mininet.util import errRun
from mininet.moduledeps import pathCheck

setLogLevel("info")

net = Mininet(controller=Controller, switch=OVSKernelSwitch, host=Host, link=TCLink)



class LinuxRouter(Node):
    def config(self, **params):
        super().config(**params)
        self.cmd('sysctl -w net.ipv4.ip_forward=1')
    def terminate(self):
        self.cmd('sysctl -w net.ipv4.ip_forward=0')
        super().terminate()


# Controllers
c1 = net.addController("c1", port=6633)
c2 = net.addController("c2", port=6634)

# Switches
s1 = net.addSwitch("s1", cls=OVSKernelSwitch)
s2 = net.addSwitch("s2", cls=OVSKernelSwitch)
s3 = net.addSwitch("s3", cls=OVSKernelSwitch)
s4 = net.addSwitch("s4", cls=OVSKernelSwitch)
s5 = net.addSwitch("s5", cls=OVSKernelSwitch)
s6 = net.addSwitch("s6", cls=OVSKernelSwitch)
s7 = net.addSwitch("s7", cls=OVSKernelSwitch)

# Hosts
h1 = net.addHost("h1", ip="10.0.0.1/8", mac="000000000001")
h2 = net.addHost("h2", ip="10.0.0.2/8", mac="000000000002")
h3 = net.addHost("h3", ip="10.0.0.3/8", mac="000000000003")
h4 = net.addHost("h4", ip="10.0.0.4/8", mac="000000000004")
h5 = net.addHost("h5", ip="10.0.0.5/8", mac="000000000005")
h6 = net.addHost("h6", ip="10.0.0.6/8", mac="000000000006")
h7 = net.addHost("h7", ip="10.0.0.7/8", mac="000000000007")
h8 = net.addHost("h8", ip="10.0.0.8/8", mac="000000000008")
h9 = net.addHost("h9", ip="10.0.0.9/8", mac="000000000009")
h10 = net.addHost("h10", ip="10.0.0.10/8", mac="00000000000A")
h11 = net.addHost("h11", ip="10.0.0.11/8", mac="00000000000B")
h12 = net.addHost("h12", ip="10.0.0.12/8", mac="00000000000C")
h13 = net.addHost("h13", ip="10.0.0.13/8", mac="00000000000D")
h14 = net.addHost("h14", ip="10.0.0.14/8", mac="00000000000E")
h15 = net.addHost("h15", ip="10.0.0.15/8", mac="00000000000F")
h16 = net.addHost("h16", ip="10.0.0.16/8", mac="000000000010")
h17 = net.addHost("h17", ip="10.0.0.17/8", mac="000000000011")
h18 = net.addHost("h18", ip="10.0.0.18/8", mac="000000000012")
h19 = net.addHost("h19", ip="10.0.0.19/8", mac="000000000013")
h20 = net.addHost("h20", ip="10.0.0.20/8", mac="000000000014")
h21 = net.addHost("h21", ip="10.0.0.21/8", mac="000000000015")
h22 = net.addHost("h22", ip="10.0.0.22/8", mac="000000000016")

# Routers
r1 = net.addHost("r1", cls=LinuxRouter, ip="10.0.0.101/8", mac="000000000065")

# NATs
nat1 = net.addNAT("nat1", connect=None, ip="10.0.0.201/8", mac="0000000000C9")

# Links
net.addLink(h1, s1)
net.addLink(s1, h2)
net.addLink(h3, s2)
net.addLink(s2, h4)
net.addLink(h11, s3)
net.addLink(s3, h12)
net.addLink(h13, s3)
net.addLink(h14, s3)
net.addLink(s3, h15)
net.addLink(s3, h16)
net.addLink(h5, s3)
net.addLink(s3, h6)
net.addLink(s3, h7)
net.addLink(s3, h8)
net.addLink(s3, h9)
net.addLink(s3, h10)
net.addLink(s3, s2)
net.addLink(s3, s5)
net.addLink(s4, s5)
net.addLink(r1, s7)
net.addLink(r1, s6)
net.addLink(r1, s2)
net.addLink(r1, s1)
net.addLink(nat1, s4)
net.addLink(h21, s5)
net.addLink(h22, s5)
net.addLink(s6, h18)
net.addLink(s6, h17)
net.addLink(s7, h19)
net.addLink(h20, s7)

net.build()



c1.start()
c2.start()

s1.start([c1])
s2.start([c1])
s3.start([c2])
s4.start([c2])
s5.start([c2])
s6.start([c1])
s7.start([c1])

print("\nNetwork topology created successfully!\n")

CLI(net)  # Start Mininet CLI

net.stop()
