
"""
Script generated by Mininet-GUI (https://github.com/latarc/mininet-gui)
"""
from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSKernelSwitch, Host
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel

setLogLevel("info")

net = Mininet(controller=Controller, switch=OVSKernelSwitch, host=Host, link=TCLink)

# Controllers
c1 = net.addController("c1")

# Switches
s1 = net.addSwitch("s1")
s2 = net.addSwitch("s2")
s3 = net.addSwitch("s3")

# Hosts
h1 = net.addHost("h1", ip="10.0.0.1/8", mac="000000000001")
h2 = net.addHost("h2", ip="10.0.0.2/8", mac="000000000002")
h3 = net.addHost("h3", ip="10.0.0.3/8", mac="000000000003")
h4 = net.addHost("h4", ip="10.0.0.4/8", mac="000000000004")

# Links
net.addLink(h1, s1)
net.addLink(h2, s1)
net.addLink(s2, h3)
net.addLink(s2, h4)
net.addLink(s1, s3)
net.addLink(s2, s3)

net.build()

c1.start()

s1.start([c1])
s2.start([c1])
s3.start([c1])

print("\nNetwork topology created successfully!\n")

CLI(net)  # Start Mininet CLI

net.stop()
