export const buildSystemPrompt = (graphState) => {
  const actionsDescription = [
    "Available actions:",
    "- create_host({nodes:[{x,y},...]})",
    "- create_switch({nodes:[{x,y},...]})",
    "- create_controller({nodes:[{x,y,remote,ip,port},...]})",
    "- create_link({from,to})",
    "- associate_switch({switch_id,controller_id})",
    "- get_topology({})",
    "- run_command({node_id, command})",
    "- delete_node({node_id})",
    "",
    "Topology descriptions:",
    "- Single-switch: one switch connected to k hosts.",
    "- Linear: k switches in a chain, each switch has n hosts.",
    "",
    "Example (single-switch):",
    "User prompt: 'Create a single-switch topology with 4 hosts.'",
    "Topology spec: create switch s1, create hosts h1..h4, link each host to s1.",
    "Spacing: place nodes at least 100 units apart on x/y (use -100 or +100 steps).",
    "",
    "Example coordinates:",
    "- s1 at (0, 0)",
    "- h1 at (-100, 100)",
    "- h2 at (0, 100)",
    "- h3 at (100, 100)",
    "- h4 at (200, 100)",
    "",
    "Controller creation:",
    "- Default controller: create_controller({nodes:[{x,y,remote:false}]})",
    "- Remote controller: create_controller({nodes:[{x,y,remote:true,ip:\"1.2.3.4\",port:6653}]})",
    "- Every switch created should be associated to a controller if one exists in the network.",
    "- After creating topology, call get_topology() and verify that the graph matches the intended design.",
    "",
    "Example (linear):",
    "User prompt: 'Create a linear topology with 3 switches and 2 hosts per switch.'",
    "Topology spec: create switches s1-s3 in a line, create links between s1-s2 and s2-s3 with each other. For each switch si, create hosts hj and link them to si.",
    "Spacing: switches along x by 100 units; hosts below each switch spaced by 100 units on x/y.",
    "",
    "Example coordinates:",
    "- s1 at (0, 100), s2 at (200, 100), s3 at (400, 100)",
    "- h1 at (0, 0), h2 at (100, 0)",
    "- h3 at (200, 0), h4 at (300, 0)",
    "- h5 at (400, 0), h6 at (500, 0)",
    "",
    "Topology guidance:",
    "- When creating multiple nodes, separate positions by 100 units on x and/or y (use -100 or +100 steps).",
  ].join("\n");

  const graphJson = graphState ? `Graph state (JSON): ${JSON.stringify(graphState)}` : "";
  return `${actionsDescription}\n\n${graphJson}`.trim();
};
